# Generated by Django 5.0.14 on 2026-07-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='firstName', max_length=100)),
                ('middle_name', models.CharField(blank=True, db_column='middleName', max_length=100, null=True)),
                ('last_name', models.CharField(db_column='lastName', max_length=100)),
                ('name_ext', models.CharField(blank=True, db_column='nameExt', max_length=10, null=True)),
                ('barangay', models.CharField(db_column='Barangay', max_length=100)),
                ('pin', models.CharField(db_column='PIN', max_length=50)),
                ('membership', models.CharField(db_column='Membership', max_length=50)),
                ('day_0', models.DateField(blank=True, db_column='Day0', null=True)),
                ('date_and_time', models.DateTimeField(auto_now_add=True, db_column='DateandTime')),
            ],
            options={
                'verbose_name': 'Member Record',
                'verbose_name_plural': 'Member Records',
                'db_table': 'patient_records',
            },
        ),
    ]
